[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
sort_imports = true

[profile.default]
solc_version = '0.8.24'
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
# optimizer_runs = 10_000

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
